// ==UserScript==
// @name         Bangermeter â€” X Algorithm Scorer
// @namespace    bangermeter
// @version      1.7.1
// @description  Scores posts with X's actual published For You ranking weights (xai-org/x-algorithm, Aug 13 2026 release) using the real Phoenix weighted-sum arithmetic.
// @match        https://x.com/*
// @match        https://twitter.com/*
// @grant        none
// @run-at       document-idle
// ==/UserScript==

// Single-file build generated by store-assets/make-userscript.ps1 from extension/
// (weights.js + scoring.js + content.js + styles.css) at extension v0.9.1.
// The settings popup is not available in the userscript version; defaults apply
// (badges ON, draft meter ON, theme AUTO, out-of-network OFF, mutual-follow OFF,
// 2023 verified boost OFF â€” edit BANGERMETER_DEFAULT_SETTINGS below to change).
(function () {
  var s = document.createElement('style');
  s.textContent = "/* Bangermeter — injected styles (neo-brutalist brand system)\n   Rules: hard shadows (no blur), 2-3px borders, flat opaque colors, sharp corners,\n   physical hover feedback, high contrast. No gradients, no transparency.\n   Panel + meter are theme-aware via [data-bm-theme=\"dark\"] (set from X\u0027s own theme);\n   the badge stays light deliberately — it is the brand chip. */\n\n:root {\n  --ts-black: #000000;\n  --ts-white: #FFFFFF;\n  --ts-cream: #F5F0E6;\n  --ts-red: #FF5252;\n  --ts-yellow: #FFEB3B;\n  --ts-blue: #2196F3;\n  --ts-green: #4CAF50;\n  --ts-orange: #FF9800;\n  /* Font stacks intentionally rely on locally-installed fonts with strong\n     fallbacks (Arial Black / Impact / Arial) — a content script should not\n     phone home to a font CDN. */\n  --ts-font-display: \u0027Archivo Black\u0027, \u0027Arial Black\u0027, Impact, sans-serif;\n  --ts-font-body: \u0027Space Grotesk\u0027, Arial, sans-serif;\n}\n\n/* Theme tokens: light defaults, dark overrides */\n.bangermeter-panel,\n.bangermeter-meter {\n  --bm-surface: #FFFFFF;\n  --bm-text: #000000;\n  --bm-ink: #555555;\n  --bm-line: #000000;\n  --bm-shadow: #000000;\n  --bm-up: #2E7D32;\n  --bm-down: #C62828;\n  --bm-barpos: #C8E6C9;\n  --bm-barneg: #FFCDD2;\n  --bm-link: #2196F3;\n}\n.bangermeter-panel[data-bm-theme=\"dark\"],\n.bangermeter-meter[data-bm-theme=\"dark\"] {\n  --bm-surface: #1C1C1C;\n  --bm-text: #FFFFFF;\n  --bm-ink: #B8B8B8;\n  --bm-line: #FFFFFF;\n  --bm-shadow: #FFFFFF;\n  --bm-up: #7DDB82;\n  --bm-down: #FF8A80;\n  --bm-barpos: #1E4620;\n  --bm-barneg: #5A1F1F;\n  --bm-link: #64B5F6;\n}\n\n/* ── Badge (always light — the brand chip) ─────────────────────────────── */\n\n.bangermeter-badge {\n  display: inline-flex;\n  align-items: center;\n  gap: 5px;\n  margin-left: 10px;\n  padding: 2px 7px;\n  border-radius: 0;\n  background: var(--ts-white);\n  border: 2px solid var(--ts-black);\n  box-shadow: 2px 2px 0 var(--ts-black);\n  font-family: var(--ts-font-body);\n  font-size: 12px;\n  font-weight: 700;\n  line-height: 16px;\n  color: var(--ts-black);\n  cursor: pointer;\n  user-select: none;\n  align-self: center;\n  transition: transform 0.1s ease, box-shadow 0.1s ease;\n}\n.bangermeter-badge:hover {\n  transform: translate(-1px, -1px);\n  box-shadow: 3px 3px 0 var(--ts-black);\n}\n.bangermeter-badge:active {\n  transform: translate(1px, 1px);\n  box-shadow: 1px 1px 0 var(--ts-black);\n}\n.bangermeter-badge:focus-visible {\n  outline: 3px solid var(--ts-blue);\n  outline-offset: 2px;\n}\n\n.bangermeter-icon { display: inline-flex; align-items: center; }\n.bangermeter-icon svg { width: 12px; height: 12px; display: block; }\n\n/* The brand mark: bolt is ALWAYS black on yellow, regardless of surrounding\n   text color (fixes white-bolt bug in the black header). */\n.bangermeter-bolt-box {\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  width: 16px;\n  height: 16px;\n  background: var(--ts-yellow);\n  border: 2px solid var(--ts-black);\n  color: var(--ts-black);\n  flex: none;\n}\n.bangermeter-bolt-box svg { width: 10px; height: 10px; display: block; }\n\n/* Score chips: flat neo color + black text + black border (both themes) */\n.bangermeter-seg {\n  padding: 0 4px;\n  border: 2px solid var(--ts-black);\n  color: var(--ts-black);\n  font-weight: 700;\n}\n.bangermeter-high { background: var(--ts-green); }\n.bangermeter-mid { background: var(--ts-yellow); }\n.bangermeter-low { background: var(--ts-red); }\n\n/* ── Breakdown panel ───────────────────────────────────────────────────── */\n\n.bangermeter-panel {\n  position: fixed;\n  z-index: 2147483647;\n  width: 380px;\n  max-height: 70vh;\n  overflow-y: auto;\n  background: var(--bm-surface);\n  color: var(--bm-text);\n  border: 3px solid var(--bm-line);\n  border-radius: 0;\n  box-shadow: 8px 8px 0 var(--bm-shadow);\n  font-family: var(--ts-font-body);\n  font-size: 13px;\n  padding: 0 0 8px 0;\n}\n\n/* Neo scrollbar: square yellow thumb, thick rails */\n.bangermeter-panel::-webkit-scrollbar { width: 14px; }\n.bangermeter-panel::-webkit-scrollbar-track {\n  background: var(--bm-surface);\n  border-left: 2px solid var(--bm-line);\n}\n.bangermeter-panel::-webkit-scrollbar-thumb {\n  background: var(--ts-yellow);\n  border: 2px solid var(--bm-line);\n  border-radius: 0;\n}\n.bangermeter-panel::-webkit-scrollbar-thumb:hover { background: var(--ts-orange); }\n\n.bangermeter-panel-head {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  padding: 10px 14px;\n  border-bottom: 3px solid var(--bm-line);\n  position: sticky;\n  top: 0;\n  z-index: 2;\n  background: var(--ts-black);\n}\n.bangermeter-panel-title {\n  display: inline-flex;\n  align-items: center;\n  gap: 8px;\n  font-family: var(--ts-font-display);\n  font-weight: 400;\n  font-size: 14px;\n  letter-spacing: 0.04em;\n  text-transform: uppercase;\n  color: var(--ts-white);\n}\n\n.bangermeter-panel-close {\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  border: 2px solid var(--ts-black);\n  background: var(--ts-yellow);\n  color: var(--ts-black);\n  cursor: pointer;\n  width: 26px;\n  height: 26px;\n  padding: 0;\n  border-radius: 0;\n  box-shadow: 2px 2px 0 var(--ts-white);\n  transition: transform 0.1s ease, box-shadow 0.1s ease;\n  flex: none;\n}\n.bangermeter-panel-close svg { width: 12px; height: 12px; display: block; }\n.bangermeter-panel-close:hover {\n  transform: translate(-1px, -1px);\n  box-shadow: 3px 3px 0 var(--ts-white);\n}\n.bangermeter-panel-close:active {\n  transform: translate(1px, 1px);\n  box-shadow: 1px 1px 0 var(--ts-white);\n}\n.bangermeter-panel-close:focus-visible {\n  outline: 3px solid var(--ts-blue);\n  outline-offset: 2px;\n}\n\n.bangermeter-panel-section {\n  padding: 12px 14px;\n  border-bottom: 2px solid var(--bm-line);\n}\n.bangermeter-panel-section:last-child { border-bottom: none; }\n\n.bangermeter-panel-scorerow {\n  display: flex;\n  align-items: center;\n  gap: 10px;\n  margin-bottom: 8px;\n}\n.bangermeter-panel-scorelabel {\n  font-family: var(--ts-font-display);\n  font-weight: 400;\n  font-size: 13px;\n  text-transform: uppercase;\n  letter-spacing: 0.03em;\n}\n.bangermeter-panel-scoreval {\n  font-family: var(--ts-font-display);\n  font-weight: 400;\n  font-size: 20px;\n  line-height: 1.2;\n  padding: 1px 10px;\n  border: 2px solid var(--ts-black);\n  box-shadow: 2px 2px 0 var(--bm-shadow);\n  margin-left: auto;\n  color: var(--ts-black);\n}\n\n.bangermeter-sub {\n  font-size: 11.5px;\n  color: var(--bm-ink);\n  margin: 0 0 8px;\n  line-height: 1.4;\n}\n\n/* Contribution rows (inside \"Show the math\") */\n.bangermeter-contrib {\n  position: relative;\n  display: flex;\n  align-items: center;\n  gap: 6px;\n  padding: 2px 0;\n  min-height: 18px;\n}\n.bangermeter-contrib-bar {\n  position: absolute;\n  left: 0;\n  top: 2px;\n  bottom: 2px;\n  background: var(--bm-barpos);\n  border-radius: 0;\n  z-index: 0;\n}\n.bangermeter-contrib-bar.bangermeter-neg { background: var(--bm-barneg); }\n.bangermeter-contrib-label { position: relative; z-index: 1; flex: 1; font-size: 12px; }\n.bangermeter-contrib-val {\n  position: relative;\n  z-index: 1;\n  font-variant-numeric: tabular-nums;\n  font-size: 11px;\n  color: var(--bm-ink);\n}\n\n.bangermeter-subhead {\n  font-family: var(--ts-font-display);\n  font-weight: 400;\n  font-size: 11px;\n  text-transform: uppercase;\n  letter-spacing: 0.04em;\n  margin: 8px 0 4px;\n}\n\n.bangermeter-mod { display: flex; gap: 6px; padding: 2px 0; font-size: 12.5px; align-items: baseline; }\n.bangermeter-mod-dir { width: 14px; text-align: center; font-weight: 700; flex: none; }\n.bangermeter-mod-label { flex: 1; }\n.bangermeter-up { color: var(--bm-up); }\n.bangermeter-down { color: var(--bm-down); }\n\n/* Rescorer callout: yellow highlight bar (both themes — brand) */\n.bangermeter-rescorer {\n  display: inline-block;\n  margin-top: 8px;\n  font-size: 12px;\n  font-weight: 700;\n  color: var(--ts-black);\n  background: var(--ts-yellow);\n  border: 2px solid var(--ts-black);\n  padding: 2px 8px;\n}\n\n.bangermeter-unweighted { margin-top: 6px; font-size: 12px; color: var(--bm-ink); }\n.bangermeter-context {\n  display: flex;\n  align-items: center;\n  gap: 6px;\n  font-size: 12px;\n  font-weight: 700;\n  margin-bottom: 6px;\n}\n.bangermeter-context .bangermeter-icon svg { width: 14px; height: 14px; }\n.bangermeter-fineprint { font-size: 11px; color: var(--bm-ink); margin-top: 6px; line-height: 1.4; }\n\n.bangermeter-plainrow {\n  display: flex;\n  gap: 7px;\n  padding: 3px 0;\n  font-size: 12.5px;\n  align-items: flex-start;\n}\n.bangermeter-plainrow .bangermeter-icon { margin-top: 2px; }\n.bangermeter-plainrow .bangermeter-icon svg { width: 14px; height: 14px; }\n.bangermeter-plainrow \u003e span:not(.bangermeter-icon):not(.bangermeter-worth) {\n  white-space: nowrap;\n  flex: none;\n}\n.bangermeter-worth { color: var(--bm-ink); font-size: 11.5px; flex: 1 1 140px; min-width: 140px; }\n\n/* Expandable math sections */\n.bangermeter-math { margin-top: 10px; }\n.bangermeter-math summary {\n  cursor: pointer;\n  font-family: var(--ts-font-display);\n  font-weight: 400;\n  font-size: 11px;\n  text-transform: uppercase;\n  letter-spacing: 0.03em;\n  color: var(--bm-link);\n  user-select: none;\n  list-style: none;\n}\n.bangermeter-math summary:hover { text-decoration: underline; }\n.bangermeter-math summary::-webkit-details-marker { display: none; }\n.bangermeter-math summary::before { content: \"+ \"; }\n.bangermeter-math[open] summary::before { content: \"− \"; }\n.bangermeter-math summary:focus-visible {\n  outline: 3px solid var(--ts-blue);\n  outline-offset: 2px;\n}\n\n/* ── Compose meter ─────────────────────────────────────────────────────── */\n\n/* Pinned to the viewport rather than inserted inline. X\u0027s composer lives inside\n   a scrolling, overflow-hidden dialog with a toolbar layered over the bottom of\n   it, so an inline meter gets clipped or covered as the draft grows. Fixed\n   positioning + clamping in content.js makes that structurally impossible.\n   pointer-events:none so a chip floating over the composer can never eat a\n   click meant for the text area or the Post button. */\n.bangermeter-meter {\n  position: fixed;\n  z-index: 2147483646;\n  display: flex;\n  align-items: center;\n  gap: 8px;\n  margin: 0;\n  padding: 6px 10px;\n  max-width: 560px;\n  background: var(--bm-surface);\n  border: 2px solid var(--bm-line);\n  box-shadow: 3px 3px 0 var(--bm-shadow);\n  font-family: var(--ts-font-body);\n  font-size: 12px;\n  color: var(--bm-text);\n  pointer-events: none;\n}\n.bangermeter-meter.bangermeter-hidden { display: none; }\n.bangermeter-meter-track {\n  flex: 0 0 90px;\n  height: 12px;\n  border-radius: 0;\n  background: var(--bm-surface);\n  border: 2px solid var(--bm-line);\n  box-shadow: 2px 2px 0 var(--bm-shadow);\n  overflow: hidden;\n}\n.bangermeter-meter-fill { height: 100%; border-radius: 0; transition: width 0.2s ease; }\n.bangermeter-fill-high { background: var(--ts-green); }\n.bangermeter-fill-mid { background: var(--ts-yellow); }\n.bangermeter-fill-low { background: var(--ts-red); }\n.bangermeter-meter-score {\n  display: inline-flex;\n  align-items: center;\n  gap: 4px;\n  font-weight: 700;\n}\n.bangermeter-meter-hints {\n  display: flex;\n  gap: 10px;\n  font-weight: 600;\n  white-space: nowrap;\n  overflow: hidden;\n  text-overflow: ellipsis;\n}\n\n/* ── Motion preferences ────────────────────────────────────────────────── */\n\n@media (prefers-reduced-motion: reduce) {\n  .bangermeter-badge, .bangermeter-panel-close, .bangermeter-meter-fill {\n    transition: none;\n  }\n  .bangermeter-badge:hover, .bangermeter-panel-close:hover {\n    transform: none;\n  }\n}\n";
  (document.head || document.documentElement).appendChild(s);
})();

// Bangermeter — weight configuration (single source of truth)
//
// TWO STRICTLY SEPARATE LAYERS:
//   1. WEIGHT LAYER  — the published algorithm values. Never invented.
//   2. ESTIMATOR LAYER — how we approximate P(action) from what a browser can see.
//      Clearly labeled estimates; the honesty boundary lives here.
//
// Provenance codes:
//   "2026-published" — transcribed verbatim from xai-org/x-algorithm,
//                      home-mixer/params/param.rs (the Aug 13, 2026 release).
//   "2026-config"    — constant from home-mixer/params/config.rs.
//   "2023-archived"  — 2023-era code, removed from the current release; opt-in only.
//   "earlybird-archived" — Earlybird-era constant from twitter/the-algorithm; display context only.
//   "2026-studies"   — external causal research, not an X parameter.
//   "estimate"       — estimator-layer number (baseline rates / directional modifiers).

var BANGERMETER_CONFIG = {
  version: "0.9.1",

  // ── PROVENANCE ──────────────────────────────────────────────────────────────
  // On August 13, 2026 X published the actual production ranking weights for the
  // first time. This supersedes the April 2023 snapshot every version of this
  // tool used through v0.8.0.
  //
  // param.rs header, verbatim:
  //   "// mirrored from config feature-switch defaults; last sync 2026-08-12T04:09:22Z"
  //
  // README, verbatim:
  //   "To enable experimentation, many tunable values are read from a configuration
  //    system rather than written into the code. To help people understand the
  //    production defaults, we run cron scripts that set the defaults in this
  //    repository's code to be the primary production values, for example in
  //    home-mixer/params/param.rs."
  //
  // That is a materially stronger claim than the 2023 release made — these are
  // asserted to BE the production values, not merely plausible defaults.
  weightsSnapshot: "August 13, 2026 — xai-org/x-algorithm, home-mixer/params/param.rs (feature-switch sync 2026-08-12T04:09:22Z)",
  weightsSourceUrl: "https://github.com/xai-org/x-algorithm/blob/main/home-mixer/params/param.rs",
  scorerSourceUrl: "https://github.com/xai-org/x-algorithm/blob/main/home-mixer/scorers/ranking_scorer.rs",

  // X's own framing of what these numbers mean (param.rs, above the weight block):
  //   "These weights reflect a combination of how much an action is valued in
  //    ranking and typical propensities of these actions across the X network
  //    (e.g. negative feedback is overall rare)."
  // i.e. report = -234 is large PARTLY because reports are rare. The weight is not
  // a "penalty per report" — it is a coefficient on a predicted probability.
  weightsMeaningNote: "Weights multiply a PREDICTED PROBABILITY, not a count. X states the values already fold in how rare each action typically is.",

  // ── WEIGHT LAYER ────────────────────────────────────────────────────────────
  // Phoenix heads. Score = Σ(weight × P(action)), ranking_scorer.rs:471-511.
  // `observable` marks heads a browser extension can actually derive from the DOM.
  heads: {
    favorite: { weight: 0.5, param: "rust_home_mixer_favorite_weight",
      provenance: "2026-published", label: "Likes", observable: true },
    reply: { weight: 5.0, param: "rust_home_mixer_reply_weight",
      provenance: "2026-published", label: "Replies", observable: true,
      note: "Rises to 20.0 (+15.0) on an ORIGINAL post from an author you mutually follow — see bidirectionalFollowReplyBoost. Down from 13.5 in the 2023 table." },
    retweet: { weight: 1.0, param: "rust_home_mixer_retweet_weight",
      provenance: "2026-published", label: "Reposts", observable: true },
    quote: { weight: 5.0, param: "rust_home_mixer_quote_weight",
      provenance: "2026-published", label: "Quotes",
      note: "Same weight as a reply. Quote counts are not exposed in the timeline DOM, so this is scored from the estimator only." },
    share: { weight: 2.0, param: "rust_home_mixer_share_weight",
      provenance: "2026-published", label: "Shares" },
    share_via_dm: { weight: 5.0, param: "rust_home_mixer_share_via_dm_weight",
      provenance: "2026-published", label: "Share via DM",
      note: "Per impression this is worth 10× a like and matches a reply exactly. Musk (Sep 2024) called forwarding posts to friends 'one of the strongest signals'; 5.0 puts it in the second tier, a quarter of a copy-link share — consistent with that remark, but a vague quote is not something a number can confirm." },
    share_via_copy_link: { weight: 20.0, param: "rust_home_mixer_share_via_copy_link_weight",
      provenance: "2026-published", label: "Share via copy link",
      note: "The heaviest positive weight in the table: per impression it is worth 40× a like and 4× a reply, so no single action a viewer takes is worth more. That is a claim about value per event, not about volume — copy-link shares are rare, so they move far fewer posts than likes do. Bangermeter cannot observe them at all and scores this head from a baseline estimate." },
    follow_author: { weight: 4.0, param: "rust_home_mixer_follow_author_weight",
      provenance: "2026-published", label: "Follow author" },
    click: { weight: 0.4, param: "rust_home_mixer_click_weight",
      provenance: "2026-published", label: "Post click" },
    open_link: { weight: 0.2, param: "rust_home_mixer_open_link_weight",
      provenance: "2026-published", label: "Open link",
      note: "Links ARE rewarded, contradicting the long-standing 'links are punished' folklore — though at 0.2 the reward is small, and low-context link posts still lose more on likes/replies/dwell than they gain here." },
    photo_expand: { weight: 0.05, param: "rust_home_mixer_photo_expand_weight",
      provenance: "2026-published", label: "Photo expand" },
    video_open: { weight: 0.05, param: "rust_home_mixer_video_open_weight",
      provenance: "2026-published", label: "Video open" },
    vqv: { weight: 0.05, param: "rust_home_mixer_vqv_weight",
      provenance: "2026-published", label: "Video quality view",
      note: "Two gates, both in candidates_util.rs::vqv_weight. (1) Duration must be STRICTLY GREATER than MinVideoDurationMs = 10,000 — a 10.000s clip earns nothing, and neither do GIFs. (2) If the VIEWER has ≥10,000 followers (MAX_FOLLOWERS_THRESHOLD), the weight is forced to 0 outright — large accounts earn no video-quality-view credit from their own feed at all." },
    quoted_click: { weight: 0.05, param: "rust_home_mixer_quoted_click_weight",
      provenance: "2026-published", label: "Quoted-post click" },
    post_unexplored: { weight: 0.02, param: "rust_home_mixer_post_unexplored_weight",
      provenance: "2026-published", label: "Post unexplored",
      note: "In-network only (PostUnexploredWeightInNetworkOnly = true). Viewer-specific novelty — excluded from the content score." },
    cont_dwell_time: { weight: 0.004, param: "rust_home_mixer_cont_dwell_time_weight",
      provenance: "2026-published", label: "Dwell time",
      continuous: true,
      note: "CONTINUOUS head: multiplies predicted dwell in seconds, not a probability. At a few seconds of dwell this is one of the largest terms for an ordinary post." },

    // Heads X ships with an explicit 0.0 — they exist, they are wired in, and they
    // currently contribute exactly nothing. That is a finding, not an omission.
    profile_click: { weight: 0.0, param: "rust_home_mixer_profile_click_weight",
      provenance: "2026-published", label: "Profile click",
      note: "ZEROED. The 2023 table paid 12.0 for a profile-click-and-engage. It is now worth nothing." },
    dwell: { weight: 0.0, param: "rust_home_mixer_dwell_weight",
      provenance: "2026-published", label: "Dwell (binary)",
      note: "ZEROED. Binary dwell pays nothing; only continuous dwell TIME is paid, via cont_dwell_time." },
    quoted_vqv: { weight: 0.0, param: "rust_home_mixer_quoted_vqv_weight",
      provenance: "2026-published", label: "Quoted video quality view", note: "ZEROED." },
    cont_click_dwell_time: { weight: 0.0, param: "rust_home_mixer_cont_click_dwell_time_weight",
      provenance: "2026-published", label: "Click dwell time", continuous: true, note: "ZEROED." },
    cont_active_secs_5m_residual_norm: { weight: 0.0, param: "rust_home_mixer_cont_active_secs_5m_residual_norm_weight",
      provenance: "2026-published", label: "Active seconds (5m residual)", continuous: true, note: "ZEROED." },

    // Negative heads.
    not_interested: { weight: -43.2, param: "rust_home_mixer_not_interested_weight",
      provenance: "2026-published", label: "Not interested" },
    block_author: { weight: -31.2, param: "rust_home_mixer_block_author_weight",
      provenance: "2026-published", label: "Block author",
      note: "The long-circulated 'block = -120' figure was a fan-site fabrication. The real number is -31.2 — and it is the mildest of the four hard negatives." },
    mute_author: { weight: -58.8, param: "rust_home_mixer_mute_author_weight",
      provenance: "2026-published", label: "Mute author",
      note: "Nearly 2× a block. Muting is the harsher signal, which is the reverse of what most people assume." },
    report: { weight: -234.0, param: "rust_home_mixer_report_weight",
      provenance: "2026-published", label: "Report" },
    not_dwelled: { weight: -0.02, param: "rust_home_mixer_not_dwelled_weight",
      provenance: "2026-published", label: "Not dwelled",
      note: "Scrolling straight past is now a scored penalty. Tiny per impression, but it applies to the majority of impressions, so in aggregate it is the largest negative an ordinary post carries." }
  },

  // reply_weight_for(candidate), ranking_scorer.rs:186-193. Applies ONLY when the
  // candidate is an original post (not a reply, not a repost) AND the author is a
  // mutual follow. 5.0 + 15.0 = 20.0.
  bidirectionalFollowReplyBoost: 15.0,
  // dwell_weight_for(candidate) — same gate, but shipped at 0.0, so it is inert.
  bidirectionalFollowDwellBoost: 0.0,

  // NEGATIVE_SCORES_OFFSET, home-mixer/params/config.rs.
  negativeScoresOffset: 0.001,

  // ScoringWeights::new, ranking_scorer.rs:105-128. Note what is NOT here:
  // the cont_* heads and the bidirectional boost are excluded from positive_sum.
  // These sums only matter on the negative branch of offset_score, where they
  // rescale any net-negative post into (0, offset) — below every positive post.
  weightSumMembers: {
    positive: ["favorite", "reply", "retweet", "photo_expand", "video_open", "click",
      "open_link", "profile_click", "vqv", "share", "share_via_dm", "share_via_copy_link",
      "dwell", "quote", "quoted_click", "quoted_vqv", "follow_author", "post_unexplored"],
    negative: ["not_interested", "block_author", "mute_author", "report", "not_dwelled"]
  },

  // Rescoring applied AFTER the weighted sum (ranking_scorer.rs:743-853).
  // Order in production: author diversity, then the OON factor.
  rescorers: {
    // OonWeightFactor. oon_applies() returns true for out-of-network posts AND —
    // because EnableOonRescoreForInNetworkRepliesRetweets defaults true — for
    // in-network replies and reposts. It is a boolean gate: the factor is applied
    // exactly ONCE, never squared.
    outOfNetwork: { factor: 0.75, param: "rust_home_mixer_oon_weight_factor",
      provenance: "2026-published", label: "Out-of-network / reply / repost ×0.75" },
    topicOutOfNetwork: { factor: 0.5, param: "rust_home_mixer_topic_oon_weight_factor",
      provenance: "2026-published", label: "Topic-request OON ×0.5",
      note: "Replaces the 0.75 factor entirely when the request carries topic IDs." },
    newUserOutOfNetwork: { factor: 0.00001, provenance: "2026-config", inert: true,
      label: "New-user OON ×0.00001",
      note: "NEW_USER_OON_WEIGHT_FACTOR in config.rs. INERT at published defaults: the gate requires account age < NewUserAgeThresholdSecs AND ≥5 followed users, and that threshold ships at 0, so `age < 0s` is false for every account. The mechanism exists and would annihilate out-of-network content for new accounts if the threshold were raised." },
    authorDiversity: { decay: 0.5, floor: 0.25,
      param: "rust_home_mixer_author_diversity_decay",
      floorParam: "rust_home_mixer_author_diversity_floor",
      provenance: "2026-published", label: "Author diversity decay",
      note: "(1 - floor) × decay^k + floor, where k is the author's rank among their own posts in the slate. EnableAuthorDiversity ships true and it is applied unconditionally in RankingScorer::score." },

    // NOT part of the 2026 release. 2023-era serving code (commit ec83d01dca),
    // removed Sept 2025. Opt-in only — see the v0.7.1 regression note.
    blueVerified: { inNetwork: 4.0, outOfNetwork: 2.0, provenance: "2023-archived",
      enabledBySetting: "applyVerifiedBoost2023",
      label: "Verified author boost",
      note: "BlueVerifiedAuthorInNetworkMultiplier 4.0 / OutOfNetwork 2.0 at commit ec83d01dca; absent from the 2026 code. Default off: a default-on ×4 floors every verified author near 99." },
    // Community Notes: the engagement effect of a DISPLAYED note, from three
    // independent causal studies (X's own A/B, Chuai et al. Nature Comms,
    // Slaughter et al. PNAS). Not an X ranking parameter.
    communityNote: { factor: 0.5, provenance: "2026-studies",
      label: "Community-noted ×0.5",
      note: "Three causal studies put a displayed note's effect on go-forward engagement between roughly ×0.39 and ×0.75 (Chuai et al. −61.2% reposts; Slaughter et al. −46.1% reposts / −44.1% likes; X's own A/B 25–34% fewer like/repost decisions). 0.5 is a round figure chosen inside that spread — it is our pick, not a published value. Content score only." }
  },

  // Observable signals with no head in the 2026 roster at all.
  unweightedSignals: {
    bookmark: { label: "Bookmarks",
      note: "There is NO bookmark head in the 2026 Phoenix roster — bookmarks are not a scored action. They survive only as a user-history feature (n_bm_share) inside the dwell-regret gate. Musk's 'de facto silent like' remark (Jan 2023) never became a shipped weight, and the '10×/20×' claims are folklore." }
  },

  // Facts worth surfacing that are not score components.
  sourcedFacts: {
    minVideoDurationMs: { value: 10000, param: "rust_home_mixer_min_video_duration_ms",
      provenance: "2026-published",
      note: "Video shorter than 10s earns no video-quality-view weight." },
    maxPostAgeHours: { value: 48, provenance: "2026-config",
      note: "MAX_POST_AGE in config.rs — candidates older than 48h are not retrieved." },
    resultSize: { value: 35, provenance: "2026-config",
      note: "RESULT_SIZE in config.rs — posts returned per For You request." },
    valueModelMode: { value: "weighted", param: "rust_home_mixer_value_model_mode",
      provenance: "2026-published",
      note: "The weighted sum modelled here is the shipped default. Two alternative modes exist in code (dwell_regret_sigmoid, gated_dwell_regret) with far deeper negatives (report -60000); neither is the default." },
    // Grok "banger" pipeline eligibility. NOTE: a `quality_score >= 0.4` gate was
    // asserted here through v0.8.0 and has been REMOVED — no such threshold exists
    // anywhere in the published grox pipeline, and the file it was cited to
    // (grox/classifiers/content/banger_initial_screen.py) does not exist in the repo.
    // What IS in the shipped code is the eligibility filter below.
    grox: { repliesIneligible: true, privateAccountsIneligible: true,
      provenance: "2026-published",
      source: "grox/flows/upa/task_filter.py",
      note: "TaskInitialBangerFilter rejects any post with `ancestors` (i.e. any reply) and any post from a protected account. Quality is carried as a boolean `isHighQuality`, not a numeric threshold." },
    negativeOffsetRule: {
      provenance: "ranking_scorer.rs:525-533",
      note: "Any post whose weighted sum is net-negative is rescaled into [0, 0.000894) — negative_sum/total_sum × the 0.001 offset — so it ranks below every net-positive post regardless of how good the rest of it was." }
  },

  // ── ESTIMATOR LAYER ─────────────────────────────────────────────────────────
  // Baseline P(action) per impression for a median post. ESTIMATES, not X values.
  // Calibrated so that weight × baselineP lands in a comparable band across heads,
  // which is the balance X's own note implies ("weights reflect ... typical
  // propensities"). Continuous heads (cont_dwell_time) are in SECONDS, not
  // probabilities.
  baselineP: {
    favorite: 0.005,
    reply: 0.0005,
    retweet: 0.0005,
    quote: 0.0001,
    share: 0.0004,
    share_via_dm: 0.0002,
    share_via_copy_link: 0.00005,
    follow_author: 0.0002,
    click: 0.010,
    open_link: 0.002,          // only when a link is present
    photo_expand: 0.012,       // only when an image is present
    video_open: 0.020,         // only when video is present
    vqv: 0.030,                // only when video ≥10s is present
    quoted_click: 0.004,       // only when the post quotes another
    cont_dwell_time: 3.0,      // SECONDS of predicted dwell, not a probability
    not_dwelled: 0.55,         // most impressions are scrolled past
    not_interested: 0.00005,
    block_author: 0.00001,
    mute_author: 0.00001,
    report: 0.000005,
    provenance: "estimate"
  },

  // Small-sample smoothing for the retrospective engagement score:
  //   p̂ = (count + K·p0) / (views + K)
  engagementShrinkage: { pseudoViews: 2000, provenance: "estimate" },

  // Directional content modifiers — multiply specific baseline Ps when a feature
  // is detected. `enables` marks a head that is scored ONLY when the feature is
  // present.
  contentModifiers: [
    { id: "question", label: "Asks a question", applies: "reply,quote",
      factor: 1.4, provenance: "estimate",
      why: "Questions raise expected reply rate. Reply is 5.0 — ten times a like — and quote matches it at 5.0." },
    { id: "conversation_length", label: "Substantive text (≥100 chars)",
      applies: "cont_dwell_time", factor: 1.35, provenance: "estimate",
      alsoApplies: { not_dwelled: 0.8 },
      why: "Longer posts hold attention. Dwell time is paid continuously (0.004/second) and not-dwelling is penalised (−0.02), so length moves the largest pair of terms an ordinary post has." },
    { id: "thread_starter", label: "Thread starter", applies: "click,quote",
      factor: 1.3, provenance: "estimate",
      why: "Threads drive post clicks (0.4) and give people something to quote (5.0)." },
    { id: "media_image", label: "Has image", applies: "favorite", factor: 1.1,
      provenance: "estimate", why: "Images raise like rates mildly and enable the photo-expand head (0.05)." },
    { id: "has_video", label: "Has video", applies: "", factor: 1.0,
      enables: "video_open,vqv", provenance: "2026-published",
      why: "Enables video_open (0.05), and video-quality-view (0.05) when the clip qualifies: vqv needs duration STRICTLY over 10 seconds, so GIFs and short clips earn none of it. A second gate we cannot see — the viewer having under 10,000 followers — can zero it as well. The '10× video boost' remains folklore." },
    { id: "external_link", label: "External link", applies: "", factor: 1.0,
      enables: "open_link", provenance: "2026-published",
      why: "The 2026 release pays 0.2 for opening a link — links are NOT structurally unrewarded, which retires the old 'link penalty by head omission' reading. 0.2 is small, but it is positive." },
    { id: "link_no_context", label: "Bare link (little text)",
      applies: "favorite,reply,cont_dwell_time", factor: 0.85, provenance: "estimate",
      alsoApplies: { not_dwelled: 1.2 },
      why: "A link with no context earns less on every attention head than the 0.2 open-link weight pays back. The '−30–50% link penalty' figure remains unsourced; this is a mild directional estimate." },
    { id: "many_hashtags", label: "3+ hashtags", applies: "favorite,retweet,reply",
      factor: 0.9, provenance: "estimate",
      why: "Earlybird's HAS_MULTIPLE_HASHTAGS_OR_TRENDS penalty exists in code; magnitude never published. Mild directional." },
    { id: "engagement_bait", label: "Engagement-bait phrasing",
      applies: "not_interested,mute_author", factor: 3.0, provenance: "estimate",
      why: "'Like if / RT if / follow me' phrasing invites the not-interested (−43.2) and mute (−58.8) heads, and a net-negative post is rescaled below every positive post." },
    { id: "all_caps_shout", label: "Mostly ALL-CAPS", applies: "not_interested",
      factor: 1.5, provenance: "estimate", why: "Shouting correlates with 'show less' feedback." }
  ],

  // Age decay (earlybird AgeDecay; display context only — not applied to the score)
  ageDecay: { slope: 0.003, halflifeMinutes: 360, base: 0.6, provenance: "earlybird-archived" },

  // Display normalization: 50 = the baseline median post; sqrt compresses outliers.
  display: { midpoint: 50, curve: 0.5 },

  contextNotes: {
    premium: "Verified/Premium authors see ~10× median impressions empirically (Buffer 18.8M-post study) — real, but not a term in the published formula.",
    mutualFollow: "Replies to an original post from someone you mutually follow are weighted 20.0 instead of 5.0. This is viewer-specific: the same post scores differently for a mutual than for a stranger."
  }
};

var BANGERMETER_DEFAULT_SETTINGS = {
  showBadges: true,
  scoreDrafts: true,
  assumeOutOfNetwork: false,
  assumeMutualFollow: false,
  applyVerifiedBoost2023: false,
  theme: "auto"
};

// Derived weight sums, built exactly as ScoringWeights::new does.
(function (C) {
  function sum(names) {
    return names.reduce(function (acc, n) { return acc + C.heads[n].weight; }, 0);
  }
  var positive = sum(C.weightSumMembers.positive);
  var negative = -sum(C.weightSumMembers.negative);
  C.weightSums = {
    positive: positive,
    negative: negative,
    total: positive + negative,
    positiveMembers: C.weightSumMembers.positive,
    negativeMembers: C.weightSumMembers.negative
  };
})(BANGERMETER_CONFIG);

// Bangermeter — scoring engine (pure functions, no DOM access)
//
// Implements the Phoenix weighted-value-model math from
// xai-org/x-algorithm, home-mixer/scorers/ranking_scorer.rs:
//   Score = offset_score( Σ(weight_i × P(action_i)) )
// plus the post-hoc rescoring chain (author diversity, then the OON factor).
//
// The weights are X's. The probabilities are ours — a browser can observe counts
// and content, not a Phoenix inference. Everything in the estimator layer is
// labelled as such in weights.js.

var BangermeterEngine = (function () {
  var C = BANGERMETER_CONFIG;

  // ---- helpers --------------------------------------------------------------

  // "1,234" | "12.3K" | "4.5M" | "12,3 K" -> number
  //
  // A comma is ambiguous: "1,234" is a thousands separator but "12,3 K" is a
  // decimal comma. Deciding by what FOLLOWS it — 3 digits means thousands, 1-2
  // means decimal — gets both right. Stripping commas first (as this did through
  // v0.8.0) silently turned "12,3 K" into 123,000.
  function parseCount(str) {
    if (str == null) return null;
    var s = String(str).trim().replace(/[\s  ]/g, "").toUpperCase();
    if (s === "") return null;

    var mult = 1;
    if (s.endsWith("K")) { mult = 1e3; s = s.slice(0, -1); }
    else if (s.endsWith("M")) { mult = 1e6; s = s.slice(0, -1); }
    else if (s.endsWith("B")) { mult = 1e9; s = s.slice(0, -1); }

    var hasDot = s.indexOf(".") !== -1;
    var commas = (s.match(/,/g) || []).length;
    if (hasDot) {
      // Both present: whichever comes last is the decimal separator.
      s = s.lastIndexOf(",") > s.lastIndexOf(".")
        ? s.replace(/\./g, "").replace(",", ".")
        : s.replace(/,/g, "");
    } else if (commas === 1 && /,\d{1,2}$/.test(s)) {
      s = s.replace(",", ".");   // decimal comma
    } else {
      s = s.replace(/,/g, "");   // thousands separators
    }

    var n = parseFloat(s);
    return isNaN(n) ? null : Math.round(n * mult);
  }

  function clamp(x, lo, hi) { return Math.max(lo, Math.min(hi, x)); }

  // ---- published weight lookups ---------------------------------------------

  // reply_weight_for(candidate) — ranking_scorer.rs:186-193.
  // The +15.0 boost lands only on an ORIGINAL post whose author you mutually
  // follow. Replies and reposts are explicitly ineligible.
  function replyWeightFor(ctx) {
    var base = C.heads.reply.weight;
    var boost = C.bidirectionalFollowReplyBoost;
    if (boost !== 0 && ctx && ctx.isMutualFollow === true && !ctx.isReply && !ctx.isRepost) {
      return base + boost;
    }
    return base;
  }

  // oon_applies(candidate) — ranking_scorer.rs:747-754. A boolean gate, so the
  // 0.75 factor lands exactly once. EnableOonRescoreForInNetworkRepliesRetweets
  // defaults true, which is why an in-network reply or repost is discounted too.
  function oonApplies(ctx) {
    if (!ctx) return false;
    if (ctx.inNetwork === false) return true;
    if (ctx.inNetwork === true) return !!(ctx.isReply || ctx.isRepost);
    return false;
  }

  // diversity_multiplier(decay, floor, k) — ranking_scorer.rs:614-616
  function diversityMultiplier(k) {
    var d = C.rescorers.authorDiversity;
    return (1.0 - d.floor) * Math.pow(d.decay, k) + d.floor;
  }

  // offset_score(combined) — ranking_scorer.rs:525-533.
  // The sums come from the FULL published weight table, exactly as
  // ScoringWeights::new builds them — not from the subset of heads we happen to
  // be able to estimate. That is what makes the negative branch faithful: any
  // net-negative post is squashed into (0, offset), below every positive post.
  function offsetScore(combined) {
    var w = C.weightSums;
    var off = C.negativeScoresOffset;
    if (w.total === 0) return Math.max(combined, 0);
    if (combined < 0) return (combined + w.negative) / w.total * off;
    return combined + off;
  }

  // ---- the weighted sum -----------------------------------------------------
  // headPs: { headName: { weight, p } }  (p null = head not scored)
  function weightedScore(headPs) {
    var contributions = [];
    var pos = 0, neg = 0;

    Object.keys(headPs).forEach(function (name) {
      var h = headPs[name];
      if (h == null || h.p == null) return;
      var contrib = h.weight * h.p;
      // Production splits terms by SIGN OF THE TERM, not sign of the weight.
      if (contrib >= 0) pos += contrib; else neg -= contrib;
      if (h.weight !== 0) {
        contributions.push({ head: name, p: h.p, weight: h.weight, contribution: contrib });
      }
    });

    var combined = pos - neg;
    contributions.sort(function (a, b) {
      return Math.abs(b.contribution) - Math.abs(a.contribution);
    });
    return { raw: offsetScore(combined), combined: combined, pos: pos, neg: neg,
      contributions: contributions };
  }

  // offset_score is left bit-faithful, which means the deepest possible negative
  // lands a hair below zero (float error on negative_sum). Math.pow of a negative
  // base at a fractional exponent is NaN, so the guard belongs here, at the
  // display boundary — not inside the published arithmetic.
  function normalize(raw, baselineRaw) {
    if (!(baselineRaw > 0) || !(raw > 0)) return 0;
    return Math.round(clamp(C.display.midpoint * Math.pow(raw / baselineRaw, C.display.curve), 0, 100));
  }

  // Earlybird AgeDecay.compute(base, maxBoost=1, halflife, slope, age) — exact sigmoid
  function ageDecayFactor(ageMinutes) {
    var a = C.ageDecay;
    return a.base + ((1.0 - a.base) / (1 + Math.exp(a.slope * (ageMinutes - a.halflifeMinutes))));
  }

  // ---- shared rescoring chain ----------------------------------------------
  // Production order: author diversity, then the OON factor (ranking_scorer.rs:832-853).
  // Author diversity is slate-relative (needs the whole timeline), so it is
  // reported as context rather than applied to a single post's score.
  function applyRescorers(raw, features, settings, opts) {
    var rescorers = [];
    var s = settings || {};
    var netCtx = {
      inNetwork: s.assumeOutOfNetwork ? false : true,
      isReply: !!features.isReply,
      isRepost: !!features.isRepost
    };

    if (oonApplies(netCtx)) {
      var oon = C.rescorers.outOfNetwork;
      raw *= oon.factor;
      rescorers.push({
        label: oon.label,
        factor: oon.factor,
        reason: netCtx.inNetwork === false
          ? "Out-of-network view assumed"
          : (features.isReply ? "In-network reply" : "In-network repost")
      });
    }

    if (features.isVerified && s.applyVerifiedBoost2023) {
      var bv = C.rescorers.blueVerified;
      var bvFactor = s.assumeOutOfNetwork ? bv.outOfNetwork : bv.inNetwork;
      raw *= bvFactor;
      rescorers.push({ label: "Verified author ×" + bvFactor + " (2023 code, absent from the 2026 release)",
        factor: bvFactor });
    }

    // Community Note suppression applies to the PROSPECTIVE score only — a post's
    // actual counts already embed whatever suppression occurred.
    if (opts && opts.allowCommunityNote && features.hasCommunityNote) {
      var cn = C.rescorers.communityNote;
      raw *= cn.factor;
      rescorers.push({ label: cn.label, factor: cn.factor });
    }

    return { raw: raw, rescorers: rescorers };
  }

  function mutualCtx(features, settings) {
    var s = settings || {};
    return {
      isMutualFollow: features.isMutualFollow === true || s.assumeMutualFollow === true,
      isReply: !!features.isReply,
      isRepost: !!features.isRepost
    };
  }

  // ---- retrospective: engagement-weighted score -----------------------------
  // Only three heads are genuinely observable from the timeline DOM: likes,
  // replies and reposts. Quote counts are not exposed there, and bookmarks have
  // no head in the 2026 roster at all.
  function engagementScore(features, settings) {
    var counts = features.counts || {};
    var views = counts.views == null ? null : Number(counts.views);
    if (views == null || !isFinite(views) || views <= 0) {
      return { available: false, reason: "View count not visible — cannot derive engagement rates." };
    }

    // Empirical-Bayes shrinkage toward each head's baseline rate:
    //   p̂ = (count + K·p0) / (views + K)
    var K = C.engagementShrinkage.pseudoViews;
    function rate(n, p0) {
      if (n == null) return null;
      // Guard against a caller that bypassed parseCount: a string count would
      // concatenate instead of add, and a NaN would poison the whole score.
      var c = Number(n);
      if (!isFinite(c) || c < 0) return null;
      return clamp((c + K * p0) / (views + K), 0, 1);
    }

    var B = C.baselineP;
    var replyW = replyWeightFor(mutualCtx(features, settings));

    var result = weightedScore({
      favorite: { weight: C.heads.favorite.weight, p: rate(counts.likes, B.favorite) },
      reply: { weight: replyW, p: rate(counts.replies, B.reply) },
      retweet: { weight: C.heads.retweet.weight, p: rate(counts.retweets, B.retweet) }
    });

    var resc = applyRescorers(result.raw, features, settings, { allowCommunityNote: false });

    // Fixed reference: a median post at baseline rates, base reply weight, no
    // rescoring. A mutual-follow post SHOULD score above this — that is the finding.
    var baseline = weightedScore({
      favorite: { weight: C.heads.favorite.weight, p: B.favorite },
      reply: { weight: C.heads.reply.weight, p: B.reply },
      retweet: { weight: C.heads.retweet.weight, p: B.retweet }
    }).raw;

    var unweightedSignals = [];
    if (counts.bookmarks != null) {
      unweightedSignals.push({
        label: "Bookmarks: " + counts.bookmarks.toLocaleString(),
        note: C.unweightedSignals.bookmark.note
      });
    }

    return {
      available: true,
      raw: resc.raw,
      score: normalize(resc.raw, baseline),
      contributions: result.contributions,
      rescorers: resc.rescorers,
      unweightedSignals: unweightedSignals,
      views: views,
      lowSample: views < K,
      smoothingNote: views < K
        ? "Only " + views.toLocaleString() + " views — rates are smoothed toward the median (empirical Bayes, K=" + K.toLocaleString() + "), so small samples can't spike or tank the score."
        : null,
      excludedNote: "Scored from the three heads a browser can see: likes (0.5), replies (" + replyW + "), reposts (1.0). The other 23 heads — shares (2.0 / 5.0 / 20.0), follows (4.0), clicks, dwell time and the negatives (−43.2 to −234.0) — need Phoenix's predictions, not counts."
    };
  }

  // ---- prospective: content score ------------------------------------------
  function analyzeText(text) {
    var t = text || "";
    var letters = t.replace(/[^A-Za-z]/g, "");
    var caps = t.replace(/[^A-Z]/g, "");
    return {
      length: t.length,
      hasQuestion: /\?/.test(t),
      isBait: /\b(like if|rt if|retweet if|repost if|follow me|follow for|drop a|comment below|tag someone|tag a friend)\b/i.test(t),
      mostlyCaps: letters.length >= 12 && caps.length / letters.length > 0.7
    };
  }

  // Is the video-quality-view head payable for this post?
  // Two gates in candidates_util.rs::vqv_weight — duration > MinVideoDurationMs,
  // and the VIEWER having under MAX_FOLLOWERS_THRESHOLD (10,000) followers. The
  // follower gate is viewer-state a page script cannot read, so it is disclosed
  // rather than modelled; the duration gate is enforced where the DOM reveals it.
  function vqvEligible(features) {
    if (!features.hasVideo) return false;
    if (features.isGif) return false;
    var minSeconds = C.sourcedFacts.minVideoDurationMs.value / 1000;
    if (features.videoSeconds != null && features.videoSeconds <= minSeconds) return false;
    return true;
  }

  // Heads scored for every post, regardless of media.
  var ALWAYS_ON = ["favorite", "reply", "retweet", "quote", "share", "share_via_dm",
    "share_via_copy_link", "follow_author", "click", "cont_dwell_time",
    "not_dwelled", "not_interested", "block_author", "mute_author", "report"];

  function contentScore(features, settings) {
    var B = C.baselineP;
    var text = analyzeText(features.text);

    var ps = {};
    ALWAYS_ON.forEach(function (h) { ps[h] = B[h]; });
    // Conditional heads — scored only when the post actually has the affordance.
    if (features.hasExternalLink) ps.open_link = B.open_link;
    if (features.hasImage && !features.hasVideo) ps.photo_expand = B.photo_expand;
    if (features.hasVideo) {
      ps.video_open = B.video_open;
      // candidates_util.rs::vqv_weight returns 0.0 unless duration is STRICTLY
      // greater than MinVideoDurationMs. GIFs never qualify; a known short
      // duration disqualifies; an unknown duration is credited but flagged,
      // since most X video clears 10s.
      if (vqvEligible(features)) ps.vqv = B.vqv;
    }
    if (features.isQuote) ps.quoted_click = B.quoted_click;

    var active = [];
    function bump(head, factor) {
      if (ps[head] != null) ps[head] = clamp(ps[head] * factor, 0, head === "cont_dwell_time" ? 600 : 1);
    }
    function applyMod(mod) {
      if (mod.applies) {
        mod.applies.split(",").forEach(function (h) { if (h) bump(h, mod.factor); });
      }
      if (mod.alsoApplies) {
        Object.keys(mod.alsoApplies).forEach(function (h) { bump(h, mod.alsoApplies[h]); });
      }
      active.push({ id: mod.id, label: mod.label, factor: mod.applies ? mod.factor : null,
        provenance: mod.provenance, why: mod.why });
    }

    C.contentModifiers.forEach(function (mod) {
      switch (mod.id) {
        case "question": if (text.hasQuestion) applyMod(mod); break;
        case "conversation_length": if (text.length >= 100) applyMod(mod); break;
        case "thread_starter": if (features.isThreadStarter) applyMod(mod); break;
        case "media_image": if (features.hasImage && !features.hasVideo) applyMod(mod); break;
        case "has_video": if (features.hasVideo) applyMod(mod); break;
        case "external_link": if (features.hasExternalLink) applyMod(mod); break;
        case "link_no_context":
          if (features.hasExternalLink && text.length < 50) applyMod(mod); break;
        case "many_hashtags": if ((features.hashtagCount || 0) >= 3) applyMod(mod); break;
        case "engagement_bait": if (text.isBait) applyMod(mod); break;
        case "all_caps_shout": if (text.mostlyCaps) applyMod(mod); break;
      }
    });

    var replyW = replyWeightFor(mutualCtx(features, settings));
    var headPs = {};
    Object.keys(ps).forEach(function (name) {
      if (ps[name] == null) return;
      headPs[name] = {
        weight: name === "reply" ? replyW : C.heads[name].weight,
        p: ps[name]
      };
    });

    var result = weightedScore(headPs);
    var resc = applyRescorers(result.raw, features, settings, { allowCommunityNote: true });

    // Fixed reference: median text-only post, base reply weight, no modifiers.
    var baseHeadPs = {};
    ALWAYS_ON.forEach(function (h) {
      baseHeadPs[h] = { weight: C.heads[h].weight, p: B[h] };
    });
    var baseline = weightedScore(baseHeadPs).raw;

    return {
      available: true,
      raw: resc.raw,
      score: normalize(resc.raw, baseline),
      combined: result.combined,
      netNegative: result.combined < 0,
      contributions: result.contributions,
      modifiers: active,
      rescorers: resc.rescorers
    };
  }

  // ---- combined per-tweet result -------------------------------------------
  function scoreTweet(features, settings) {
    var content = contentScore(features, settings);
    var engagement = engagementScore(features, settings);
    var age = null;
    if (features.ageMinutes != null) {
      age = { minutes: features.ageMinutes, factor: ageDecayFactor(features.ageMinutes) };
    }
    return { content: content, engagement: engagement, ageDecay: age, features: features };
  }

  return {
    parseCount: parseCount,
    ageDecayFactor: ageDecayFactor,
    offsetScore: offsetScore,
    weightedScore: weightedScore,
    replyWeightFor: replyWeightFor,
    oonApplies: oonApplies,
    vqvEligible: vqvEligible,
    diversityMultiplier: diversityMultiplier,
    engagementScore: engagementScore,
    contentScore: contentScore,
    scoreTweet: scoreTweet,
    analyzeText: analyzeText
  };
})();

// Bangermeter — content script: timeline badges, breakdown panel, compose meter
// Runs on x.com / twitter.com. Depends on weights.js + scoring.js (same isolated world).

(function () {
  "use strict";

  var settings = Object.assign({}, BANGERMETER_DEFAULT_SETTINGS);
  var scanTimer = null;

  try {
    chrome.storage.sync.get(BANGERMETER_DEFAULT_SETTINGS, function (stored) {
      settings = Object.assign({}, BANGERMETER_DEFAULT_SETTINGS, stored || {});
      if (!settings.showBadges) removeAllBadges();
      fullRescan();
    });
    chrome.storage.onChanged.addListener(function (changes, area) {
      if (area !== "sync") return;
      Object.keys(changes).forEach(function (k) { settings[k] = changes[k].newValue; });
      if (!settings.showBadges) removeAllBadges();
      fullRescan();
    });
  } catch (e) { /* storage unavailable — run with defaults */ }

  // ── theming ───────────────────────────────────────────────────────────────
  // Panel + meter follow X's OWN theme (default/dim/lights-out), not the OS,
  // unless the user pins light/dark in settings. The badge stays light — brand.
  function xThemeIsDark() {
    try {
      var bg = getComputedStyle(document.body).backgroundColor;
      var m = bg.match(/\d+/g);
      if (!m || m.length < 3) return false;
      var lum = 0.299 * m[0] + 0.587 * m[1] + 0.114 * m[2];
      return lum < 128;
    } catch (e) { return false; }
  }

  function applyTheme(node) {
    var mode = settings.theme || "auto";
    var dark = mode === "dark" || (mode === "auto" && xThemeIsDark());
    if (dark) node.setAttribute("data-bm-theme", "dark");
    else node.removeAttribute("data-bm-theme");
  }

  // ── tweet feature extraction ──────────────────────────────────────────────

  var COUNT_WORDS = {
    reply: "replies", replies: "replies",
    repost: "retweets", reposts: "retweets", retweet: "retweets", retweets: "retweets",
    like: "likes", likes: "likes",
    bookmark: "bookmarks", bookmarks: "bookmarks",
    view: "views", views: "views"
  };

  // "1 reply, 5 reposts, 30 likes, 2 bookmarks, 1034 views" -> counts object
  function parseAriaCounts(label) {
    var counts = {};
    if (!label) return counts;
    var re = /([\d.,]+[KMB]?)\s+([A-Za-z]+)/g, m;
    while ((m = re.exec(label)) !== null) {
      var key = COUNT_WORDS[m[2].toLowerCase()];
      if (key && counts[key] == null) counts[key] = BangermeterEngine.parseCount(m[1]);
    }
    return counts;
  }

  function extractCounts(article) {
    var counts = {};
    var group = article.querySelector('div[role="group"][aria-label]');
    if (group) counts = parseAriaCounts(group.getAttribute("aria-label"));

    // Fallbacks per button when the group label was empty
    [["reply", "replies"], ["retweet", "retweets"], ["like", "likes"],
     ["bookmark", "bookmarks"]].forEach(function (pair) {
      if (counts[pair[1]] != null) return;
      var btn = article.querySelector('button[data-testid="' + pair[0] + '"]');
      if (btn) {
        var parsed = parseAriaCounts(btn.getAttribute("aria-label"));
        if (parsed[pair[1]] != null) counts[pair[1]] = parsed[pair[1]];
      }
    });
    if (counts.views == null) {
      var analytics = article.querySelector('a[href*="/analytics"]');
      if (analytics) {
        var parsed = parseAriaCounts(analytics.getAttribute("aria-label"));
        if (parsed.views != null) counts.views = parsed.views;
      }
    }
    ["replies", "retweets", "likes", "bookmarks"].forEach(function (k) {
      if (counts[k] == null) counts[k] = 0;
    });
    return counts;
  }

  function extractFeatures(article) {
    var textEl = article.querySelector('[data-testid="tweetText"]');
    var text = textEl ? textEl.innerText : "";

    // A quote-tweet embed is a div[role="link"] card containing its own tweetText.
    // Media inside it belongs to the QUOTED tweet, not the one being scored.
    function inQuote(node) {
      var link = node.closest('div[role="link"]');
      return !!(link && link.querySelector('[data-testid="tweetText"]'));
    }
    function anyOutsideQuote(selector) {
      var nodes = article.querySelectorAll(selector);
      for (var i = 0; i < nodes.length; i++) {
        if (!inQuote(nodes[i])) return true;
      }
      return false;
    }

    var hasVideo = anyOutsideQuote('[data-testid="videoPlayer"], [data-testid="videoComponent"], video');
    var hasImage = anyOutsideQuote('[data-testid="tweetPhoto"]');

    // The video-quality-view head is gated on duration > 10s (candidates_util.rs).
    // GIFs never qualify, and X labels them explicitly. Where a duration overlay
    // is present ("0:23" / "1:04:12") we can settle it outright; otherwise the
    // duration is unknown and we say so rather than assuming it qualifies.
    var isGif = hasVideo && /(^|\s)GIF(\s|$)/.test(article.innerText.slice(0, 400));
    var videoSeconds = null;
    if (hasVideo && !isGif) {
      var durMatch = article.innerText.match(/(?:^|\s)(\d{1,2}:\d{2}(?::\d{2})?)(?:\s|$)/);
      if (durMatch) {
        var parts = durMatch[1].split(":").map(Number);
        videoSeconds = parts.length === 3
          ? parts[0] * 3600 + parts[1] * 60 + parts[2]
          : parts[0] * 60 + parts[1];
      }
    }
    var hasCard = anyOutsideQuote('[data-testid="card.wrapper"]');
    var hasTco = !!(textEl && textEl.querySelector('a[href*="//t.co/"]'));
    var linkishAnchor = false;
    if (textEl) {
      var anchors = textEl.querySelectorAll("a");
      for (var i = 0; i < anchors.length; i++) {
        var t = (anchors[i].textContent || "").trim();
        if (!/^[@#$]/.test(t) && /\w+\.[a-z]{2,}/i.test(t)) { linkishAnchor = true; break; }
      }
    }
    var hashtagCount = textEl ? textEl.querySelectorAll('a[href*="/hashtag/"]').length : 0;

    var isReply = false;
    var socialContext = article.querySelector('[data-testid="socialContext"]');
    var firstDivs = article.innerText.slice(0, 200);
    var isRepost = !!(socialContext && /reposted/i.test(socialContext.innerText));
    if (/Replying to/i.test(firstDivs) && !isRepost) {
      isReply = true;
    }

    // Does THIS post quote another? (enables the quoted-click head)
    var quoteCard = article.querySelector('div[role="link"]');
    var isQuote = !!(quoteCard && quoteCard.querySelector('[data-testid="tweetText"]'));

    var ageMinutes = null;
    var timeEl = article.querySelector("time[datetime]");
    if (timeEl) {
      var ts = Date.parse(timeEl.getAttribute("datetime"));
      if (!isNaN(ts)) ageMinutes = Math.max(0, (Date.now() - ts) / 60000);
    }

    var isThreadStarter = /🧵/.test(text) || /(^|\s)1\/\d+/.test(text);

    // Verified badge on the AUTHOR (not a quoted tweet's author)
    var isVerified = false;
    var vIcons = article.querySelectorAll('svg[data-testid="icon-verified"]');
    for (var v = 0; v < vIcons.length; v++) {
      if (!inQuote(vIcons[v])) { isVerified = true; break; }
    }

    // Community Note attached (Birdwatch pivot element)
    var hasCommunityNote = !!article.querySelector('[data-testid="birdwatch-pivot"]');

    // FOSNR restricted-reach interstitial (qualitative flag; magnitude unpublished)
    var visibilityLimited = /visibility limited/i.test(firstDivs);

    var idLink = article.querySelector('a[href*="/status/"] time');
    var tweetId = null;
    if (idLink) {
      var href = idLink.parentElement.getAttribute("href") || "";
      var idm = href.match(/status\/(\d+)/);
      if (idm) tweetId = idm[1];
    }

    return {
      tweetId: tweetId,
      text: text,
      counts: extractCounts(article),
      hasVideo: hasVideo,
      isGif: isGif,
      videoSeconds: videoSeconds,
      hasImage: hasImage,
      hasExternalLink: hasCard || hasTco || linkishAnchor,
      hashtagCount: hashtagCount,
      isReply: isReply,
      isRepost: isRepost,
      isQuote: isQuote,
      isThreadStarter: isThreadStarter,
      isVerified: isVerified,
      hasCommunityNote: hasCommunityNote,
      visibilityLimited: visibilityLimited,
      ageMinutes: ageMinutes
    };
  }

  // ── badge injection ───────────────────────────────────────────────────────

  function scoreLevel(s) { return s >= 65 ? "high" : s >= 40 ? "mid" : "low"; }

  function renderBadge(article) {
    // Same selector extractCounts uses, so badge home and count source agree;
    // unqualified fallback in case the action bar ever loses its aria-label.
    var group = article.querySelector('div[role="group"][aria-label]') ||
      article.querySelector('div[role="group"]');
    if (!group) return;

    var features = extractFeatures(article);
    var result = BangermeterEngine.scoreTweet(features, settings);

    var badge = article.querySelector(".bangermeter-badge");
    if (!badge) {
      badge = document.createElement("div");
      badge.className = "bangermeter-badge";
      badge.setAttribute("role", "button");
      badge.setAttribute("tabindex", "0");
      badge.title = "Bangermeter — click for breakdown";
      badge.addEventListener("click", function (ev) {
        ev.preventDefault();
        ev.stopPropagation();
        openPanel(article, badge);
      }, true);
      // role="button" divs don't fire click on Enter/Space by themselves
      badge.addEventListener("keydown", function (ev) {
        if (ev.key === "Enter" || ev.key === " ") {
          ev.preventDefault();
          ev.stopPropagation();
          openPanel(article, badge);
        }
      }, true);
      group.appendChild(badge);
    }

    badge.textContent = "";
    badge.appendChild(boltBox());

    var c = document.createElement("span");
    c.className = "bangermeter-seg bangermeter-" + scoreLevel(result.content.score);
    c.textContent = "C" + result.content.score;
    c.title = "Content score (prospective)";
    badge.appendChild(c);

    if (result.engagement.available) {
      var e = document.createElement("span");
      e.className = "bangermeter-seg bangermeter-" + scoreLevel(result.engagement.score);
      e.textContent = "E" + (result.engagement.lowSample ? "~" : "") + result.engagement.score;
      e.title = result.engagement.lowSample
        ? "Engagement score — low view sample, smoothed toward median"
        : "Engagement score (how the weights value actual engagement)";
      badge.appendChild(e);
    }

    article.setAttribute("data-bangermeter", features.tweetId || "scored");
  }

  function removeAllBadges() {
    document.querySelectorAll(".bangermeter-badge").forEach(function (b) { b.remove(); });
    document.querySelectorAll("[data-bangermeter]").forEach(function (a) {
      a.removeAttribute("data-bangermeter");
    });
  }

  // ── breakdown panel ───────────────────────────────────────────────────────

  var panel = null;
  var lastBadgeFocus = null;

  function el(tag, cls, text) {
    var node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text != null) node.textContent = text;
    return node;
  }

  // Inline SVG icons (static strings only — never interpolate page content here)
  var SVG_ICONS = {
    bolt: '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M13 2 4 14h6l-1 8 9-12h-6l1-8z"/></svg>',
    reply: '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M3 4h18v13h-9l-6 4v-4H3V4z"/></svg>',
    repost: '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8 3 4 7h3v7h2V7h3L8 3zm8 18 4-4h-3v-7h-2v7h-3l4 4z"/></svg>',
    like: '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 21C5.5 15.5 2 12 2 8a5 5 0 0 1 10-1 5 5 0 0 1 10 1c0 4-3.5 7.5-10 13z"/></svg>',
    bookmark: '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6 3h12v18l-6-5-6 5V3z"/></svg>',
    clock: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l4 3"/></svg>'
  };

  function icon(name) {
    var span = el("span", "bangermeter-icon");
    span.innerHTML = SVG_ICONS[name] || "";
    return span;
  }

  // Yellow square with black bolt — the brand mark
  function boltBox() {
    var box = el("span", "bangermeter-bolt-box");
    box.innerHTML = SVG_ICONS.bolt;
    return box;
  }

  function fmtP(p) {
    if (p >= 0.01) return (p * 100).toFixed(1) + "%";
    return (p * 100).toPrecision(2) + "%";
  }

  // Plain-English one-liners per detected signal (math lives in the tooltip + details)
  var PLAIN_SIGNALS = {
    question: "Asks a question — invites replies, the algorithm's favorite signal",
    conversation_length: "Meaty text — gives people a conversation to click into",
    thread_starter: "Starts a thread — keeps readers on the post longer",
    media_image: "Has a picture — small boost to likes",
    has_video: "Has video — watches barely count (0.05, and nothing under 10 seconds)",
    external_link: "Contains a link — opening it pays 0.2, small but not zero",
    link_no_context: "Mostly just a link — low-context link posts do worse",
    many_hashtags: "3+ hashtags — the old algorithm flags hashtag piles",
    engagement_bait: "“Like if…” bait — invites “show less” clicks and penalties",
    all_caps_shout: "MOSTLY CAPS — reads as shouting, invites negative feedback"
  };

  function plainRescorerText(r) {
    if (r.reason === "Out-of-network view assumed") return "Out-of-network view assumed — scored at 75%";
    if (r.reason === "In-network reply") return "This is a reply — replies take the same 75% discount as out-of-network posts";
    if (r.reason === "In-network repost") return "This is a repost — reposts take the same 75% discount as out-of-network posts";
    if (r.label.indexOf("Verified") === 0) {
      return "Verified author — ×" + r.factor + " boost per 2023 code (absent from the 2026 release)";
    }
    if (r.label.indexOf("Community-noted") === 0) {
      return "Community Note attached — future engagement suppressed ~50% (three causal studies)";
    }
    return r.label;
  }

  // Reply weight is viewer-dependent: 5.0 normally, 20.0 on an original post from
  // an author the viewer mutually follows (BidirectionalFollowReplyWeightBoost).
  function replyWorthText() {
    var w = BangermeterEngine.replyWeightFor({
      isMutualFollow: settings.assumeMutualFollow === true,
      isReply: false, isRepost: false
    });
    var likes = w / BANGERMETER_CONFIG.heads.favorite.weight;
    return settings.assumeMutualFollow
      ? "each worth " + likes + " likes (mutual-follow boost on)"
      : "each worth " + likes + " likes";
  }

  function mathDetails(summaryText) {
    var d = el("details", "bangermeter-math");
    d.appendChild(el("summary", null, summaryText || "Show the math"));
    return d;
  }

  function subtitle(parent, text) {
    parent.appendChild(el("div", "bangermeter-sub", text));
  }

  function sectionScoreRow(parent, label, score, rawNote) {
    var row = el("div", "bangermeter-panel-scorerow");
    row.appendChild(el("span", "bangermeter-panel-scorelabel", label));
    var v = el("span", "bangermeter-panel-scoreval bangermeter-" + scoreLevel(score), String(score));
    row.appendChild(v);
    if (rawNote) row.appendChild(el("span", "bangermeter-panel-raw", rawNote));
    parent.appendChild(row);
  }

  function contributionList(parent, contributions) {
    var maxAbs = 0;
    contributions.forEach(function (c) { maxAbs = Math.max(maxAbs, Math.abs(c.contribution)); });
    contributions.forEach(function (c) {
      var head = BANGERMETER_CONFIG.heads[c.head];
      var row = el("div", "bangermeter-contrib");
      var bar = el("div", "bangermeter-contrib-bar" + (c.contribution < 0 ? " bangermeter-neg" : ""));
      bar.style.width = maxAbs > 0 ? Math.round(Math.abs(c.contribution) / maxAbs * 100) + "%" : "0";
      row.appendChild(bar);
      var lbl = el("div", "bangermeter-contrib-label",
        (head ? head.label : c.head) + "  ·  w " + c.weight + " × P " + fmtP(c.p));
      row.appendChild(lbl);
      var val = el("div", "bangermeter-contrib-val", c.contribution.toFixed(4));
      row.appendChild(val);
      parent.appendChild(row);
    });
  }

  function openPanel(article, anchor) {
    closePanel();
    var features = extractFeatures(article);
    var result = BangermeterEngine.scoreTweet(features, settings);

    panel = el("div", "bangermeter-panel");
    panel.setAttribute("role", "dialog");
    panel.setAttribute("aria-label", "Bangermeter score breakdown");
    applyTheme(panel);
    lastBadgeFocus = anchor;
    var head = el("div", "bangermeter-panel-head");
    var title = el("span", "bangermeter-panel-title");
    title.appendChild(boltBox());
    title.appendChild(document.createTextNode("Bangermeter"));
    head.appendChild(title);
    var close = el("button", "bangermeter-panel-close");
    close.setAttribute("aria-label", "Close breakdown");
    // SVG × so it is optically centered (a text glyph sits on its baseline)
    close.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3.4" stroke-linecap="square" aria-hidden="true"><path d="M5.5 5.5 18.5 18.5M18.5 5.5 5.5 18.5"/></svg>';
    close.addEventListener("click", closePanel);
    head.appendChild(close);
    panel.appendChild(head);

    // ── Content appeal (plain English; math collapsed) ──
    var sec1 = el("div", "bangermeter-panel-section");
    sectionScoreRow(sec1, "Content appeal", result.content.score, null);
    subtitle(sec1, "What the algorithm would predict from the content alone. 50 = a typical post.");

    if (result.content.modifiers.length) {
      result.content.modifiers.forEach(function (m) {
        var bad = (m.factor != null && m.factor < 1) ||
          m.id === "engagement_bait" || m.id === "all_caps_shout";
        var neutral = m.id === "has_video";
        var dir = neutral ? "·" : (bad ? "▼" : "▲");
        var cls = neutral ? "" : (bad ? " bangermeter-down" : " bangermeter-up");
        var mrow = el("div", "bangermeter-mod");
        mrow.appendChild(el("span", "bangermeter-mod-dir" + cls, dir));
        mrow.appendChild(el("span", "bangermeter-mod-label", PLAIN_SIGNALS[m.id] || m.label));
        mrow.title = m.why + (m.factor != null ? " (×" + m.factor + ", " + m.provenance + ")" : "");
        sec1.appendChild(mrow);
      });
    } else {
      sec1.appendChild(el("div", "bangermeter-sub", "No special signals — scored as a typical post."));
    }
    result.content.rescorers.forEach(function (r) {
      var rrow = el("div", "bangermeter-rescorer",
        (r.factor >= 1 ? "▲ " : "▼ ") + plainRescorerText(r));
      rrow.title = r.label;
      sec1.appendChild(rrow);
    });
    if (result.features.visibilityLimited) {
      var vl = el("div", "bangermeter-rescorer",
        "▼ Visibility limited by X — reach suppressed (magnitude unpublished)");
      vl.title = "FOSNR restricted-reach interstitial detected (FreedomOfSpeechNotReach.scala label taxonomy; numeric penalty never released)";
      sec1.appendChild(vl);
    }
    if (result.features.hasCommunityNote) {
      sec1.appendChild(el("div", "bangermeter-fineprint",
        "Community Note effect sourced from: X's own A/B test (25–34% fewer like/repost decisions), " +
        "Chuai et al. Nature Communications (−61% subsequent reposts), Slaughter et al. PNAS " +
        "(−46% reposts / −44% likes post-attach)."));
    }
    if (result.features.isReply) {
      var bangNote = el("div", "bangermeter-sub",
        "Replies are also filtered out of X's Grok “banger” pipeline before it runs — " +
        "it only ever evaluates original posts (grox/flows/upa/task_filter.py).");
      sec1.appendChild(bangNote);
    }

    var d1 = mathDetails();
    d1.appendChild(el("div", "bangermeter-fineprint",
      "Score = Σ(weight × P) over the Phoenix heads, then offset_score (ranking_scorer.rs), " +
      "× rescorers, normalized so a median post = 50 (√ curve, capped at 100). " +
      "Raw: " + result.content.raw.toFixed(4) +
      (result.content.netNegative
        ? " — NET NEGATIVE: X rescales any post whose weighted sum goes below zero into [0, 0.000894), which puts it under every positive-scoring post in the feed."
        : "")));
    contributionList(d1, result.content.contributions);
    sec1.appendChild(d1);
    panel.appendChild(sec1);

    // ── Earned engagement (plain English; math collapsed) ──
    var sec2 = el("div", "bangermeter-panel-section");
    if (result.engagement.available) {
      sectionScoreRow(sec2, "Earned engagement", result.engagement.score, null);
      subtitle(sec2, "How the algorithm values what this post actually earned, from " +
        result.engagement.views.toLocaleString() + " views. 50 = typical rates.");

      var counts = result.features.counts || {};
      [
        { icon: "reply", n: counts.replies, one: "reply", many: "replies",
          worth: replyWorthText(),
          tip: BANGERMETER_CONFIG.heads.reply.note },
        { icon: "repost", n: counts.retweets, one: "repost", many: "reposts",
          worth: "each worth 2 likes",
          tip: "Weight 1.0 vs 0.5 for a like (param.rs, Aug 2026)" },
        { icon: "like", n: counts.likes, one: "like", many: "likes",
          worth: "the baseline unit",
          tip: "Weight 0.5 (param.rs, Aug 2026)" },
        { icon: "bookmark", n: counts.bookmarks, one: "bookmark", many: "bookmarks",
          worth: "not a scored action at all — no bookmark head exists",
          tip: BANGERMETER_CONFIG.unweightedSignals.bookmark.note }
      ].forEach(function (r) {
        if (r.n == null) return;
        var row = el("div", "bangermeter-plainrow");
        row.appendChild(icon(r.icon));
        row.appendChild(el("span", null,
          r.n.toLocaleString() + " " + (r.n === 1 ? r.one : r.many)));
        row.appendChild(el("span", "bangermeter-worth", "— " + r.worth));
        row.title = r.tip;
        sec2.appendChild(row);
      });

      if (result.engagement.smoothingNote) {
        sec2.appendChild(el("div", "bangermeter-fineprint", result.engagement.smoothingNote));
      }
      result.engagement.rescorers.forEach(function (r) {
        var rrow = el("div", "bangermeter-rescorer",
          (r.factor >= 1 ? "▲ " : "▼ ") + plainRescorerText(r));
        rrow.title = r.label;
        sec2.appendChild(rrow);
      });

      var d2 = mathDetails();
      d2.appendChild(el("div", "bangermeter-fineprint",
        "Engagement rates = count ÷ views, smoothed toward the median with K=" +
        BANGERMETER_CONFIG.engagementShrinkage.pseudoViews.toLocaleString() +
        " pseudo-views (empirical Bayes), then run through the same weighted-sum formula. " +
        "Raw: " + result.engagement.raw.toFixed(4)));
      contributionList(d2, result.engagement.contributions);
      d2.appendChild(el("div", "bangermeter-fineprint", result.engagement.excludedNote));
      sec2.appendChild(d2);
    } else {
      sec2.appendChild(el("div", "bangermeter-panel-scorelabel", "Earned engagement"));
      sec2.appendChild(el("div", "bangermeter-sub",
        "Can't score this one — the view count isn't visible, so there's nothing to compute rates from."));
    }
    panel.appendChild(sec2);

    // ── Context footer ──
    var sec3 = el("div", "bangermeter-panel-section");
    if (result.ageDecay) {
      var ageText = result.ageDecay.minutes < 90
        ? Math.round(result.ageDecay.minutes) + " min"
        : (result.ageDecay.minutes / 60).toFixed(1) + " h";
      var fresh = el("div", "bangermeter-context");
      fresh.appendChild(icon("clock"));
      fresh.appendChild(el("span", null,
        "Freshness: ×" + result.ageDecay.factor.toFixed(2) + " at " + ageText +
        " old — posts fade over ~6 hours, never below ×0.60"));
      fresh.title = "Earlybird age-decay sigmoid: base 0.6, halflife 360 min, slope 0.003";
      sec3.appendChild(fresh);
    }
    if (result.features.isVerified && !settings.applyVerifiedBoost2023) {
      var vNote = el("div", "bangermeter-fineprint",
        "Verified author: 2023-era code boosted verified posts ×4 in-network / ×2 out-of-network. " +
        "No such multiplier appears anywhere in the Aug 2026 release. Not applied to this score — " +
        "enable “2023 verified boost” in the popup to simulate that era.");
      sec3.appendChild(vNote);
    }

    // What the Aug 13, 2026 release actually says. Every WEIGHT here is read
    // from the transcribed param.rs table; the ratios are arithmetic on those
    // weights, and they describe value PER EVENT, not how often the event
    // happens. The closing note keeps that distinction visible, because a
    // heavy weight on a rare action is not the same as a big lever.
    var H = BANGERMETER_CONFIG.heads;
    var F = BANGERMETER_CONFIG.sourcedFacts;
    var d4 = mathDetails("What X's published weights actually say");
    [
      "▲ No single action is worth more than copying a post's link — " + H.share_via_copy_link.weight +
        " per share, which is " + (H.share_via_copy_link.weight / H.favorite.weight) + " likes or " +
        (H.share_via_copy_link.weight / H.reply.weight) + " replies. It is also rare, so it decides " +
        "far fewer posts than likes do.",
      "▲ Sharing to DMs pays " + H.share_via_dm.weight + " — the same as a reply. The share menu " +
        "itself pays " + H.share.weight + ". Musk called DM-forwarding “one of the strongest " +
        "signals”; this is the second tier, a quarter of a copy-link share.",
      "▲ A reply from someone you mutually follow is worth " +
        (H.reply.weight + BANGERMETER_CONFIG.bidirectionalFollowReplyBoost) + ", not " +
        H.reply.weight + " — but only on original posts, never on replies or reposts.",
      "▲ Gaining a follower off a post pays " + H.follow_author.weight + ".",
      "▲ Opening a link pays " + H.open_link.weight + ". Small, but the “links get zero credit” " +
        "story is now provably wrong.",
      "· Profile clicks pay NOTHING (" + H.profile_click.weight + "). The 2023 table paid 12.0 " +
        "for a profile-click-and-engage — that head has been zeroed out.",
      "· Binary dwell pays nothing either. Only dwell TIME pays, at " + H.cont_dwell_time.weight +
        " per second.",
      "· Video is worth " + H.vqv.weight + " per quality view, and anything under " +
        (F.minVideoDurationMs.value / 1000) + " seconds earns none of it.",
      "· Bookmarks have no head at all — they are not a scored action in 2026.",
      "▼ Scrolling straight past costs " + H.not_dwelled.weight + ". Tiny per impression, but it " +
        "happens on most of them.",
      "▼ Muting (" + H.mute_author.weight + ") hurts nearly twice as much as blocking (" +
        H.block_author.weight + "). Reporting costs " + H.report.weight + ".",
      "▼ Any post whose weighted sum goes net-negative is rescaled below every positive post, " +
        "no matter what else it earned.",
      "· Grok's “banger” pipeline only ever looks at original posts — replies and " +
        "protected accounts are filtered out before it runs."
    ].forEach(function (line) {
      var mark = line.charAt(0);
      var row = el("div", "bangermeter-mod");
      row.appendChild(el("span", "bangermeter-mod-dir" +
        (mark === "▼" ? " bangermeter-down" : mark === "▲" ? " bangermeter-up" : ""), mark));
      row.appendChild(el("span", "bangermeter-mod-label", line.slice(2)));
      d4.appendChild(row);
    });
    d4.appendChild(el("div", "bangermeter-fineprint",
      BANGERMETER_CONFIG.weightsMeaningNote + " These are values per event, not per post: a " +
      "heavy weight on a rare action still moves fewer posts than a light weight on a common " +
      "one. Only likes, replies and reposts above come from this post's real counts — the rest " +
      "need Phoenix's own predictions, so they inform what you read here without entering the " +
      "score above."));
    sec3.appendChild(d4);

    var d3 = mathDetails("About these scores");
    d3.appendChild(el("div", "bangermeter-fineprint",
      "Weights: " + BANGERMETER_CONFIG.weightsSnapshot + ". X states these are kept in sync with " +
      "the live production configuration by cron, which makes them the first ranking weights ever " +
      "published as current rather than historical."));
    d3.appendChild(el("div", "bangermeter-fineprint",
      "Alternative scoring modes exist in the same code (dwell-regret, with far deeper negatives). " +
      "The shipped default is the weighted sum modelled here (value_model_mode = “" +
      F.valueModelMode.value + "”). Relative score, not predicted reach."));
    sec3.appendChild(d3);
    panel.appendChild(sec3);

    document.body.appendChild(panel);
    var rect = anchor.getBoundingClientRect();
    var vw = window.innerWidth, vh = window.innerHeight;
    var w = panel.offsetWidth, h = panel.offsetHeight;

    // Open ABOVE the badge (top-left/top-right of the cursor) so the panel never
    // runs under the OS taskbar; fall back below only when there is clearly more
    // room under the badge than above it.
    var spaceAbove = rect.top - 16;
    var spaceBelow = vh - rect.bottom - 16;
    var placeAbove = spaceAbove >= Math.min(h, 240) || spaceAbove >= spaceBelow;
    var maxH = Math.max(120, Math.min(h, placeAbove ? spaceAbove : spaceBelow));
    panel.style.maxHeight = maxH + "px";
    // Re-measure: offsetHeight includes padding/borders on top of max-height.
    var actualH = panel.offsetHeight;
    var top = placeAbove ? rect.top - actualH - 8 : rect.bottom + 8;
    // Hard clamp: never off-screen, never under the taskbar edge.
    top = Math.max(8, Math.min(top, vh - actualH - 8));

    // Right-align to the badge so the panel extends to the LEFT of the cursor.
    var left = rect.right - w;
    left = Math.max(8, Math.min(left, vw - w - 8));

    panel.style.top = top + "px";
    panel.style.left = left + "px";

    setTimeout(function () {
      document.addEventListener("click", outsideClose, true);
      document.addEventListener("keydown", escClose, true);
    }, 0);
    // Move focus into the dialog for keyboard users
    try { close.focus({ preventScroll: true }); } catch (e) { /* focus optional */ }
  }

  function outsideClose(ev) {
    if (panel && !panel.contains(ev.target)) closePanel();
  }
  function escClose(ev) { if (ev.key === "Escape") closePanel(); }
  function closePanel() {
    var hadPanel = !!panel;
    if (panel) { panel.remove(); panel = null; }
    document.removeEventListener("click", outsideClose, true);
    document.removeEventListener("keydown", escClose, true);
    // Return focus to the badge that opened the dialog
    if (hadPanel && lastBadgeFocus && lastBadgeFocus.isConnected) {
      try { lastBadgeFocus.focus({ preventScroll: true }); } catch (e) { /* optional */ }
    }
    lastBadgeFocus = null;
  }

  // ── compose-box draft meter ───────────────────────────────────────────────

  function draftFeatures(editor, text) {
    var composeRoot = editor.closest('div[data-testid^="tweetTextarea"]');
    var scope = (composeRoot && composeRoot.parentElement && composeRoot.parentElement.parentElement) || document;
    var hasImage = !!scope.querySelector('[data-testid="attachments"] img');
    var hasVideo = !!scope.querySelector('[data-testid="attachments"] video');
    var hashtagCount = (text.match(/#[\w\u00c0-\uffff]+/g) || []).length;
    var hasExternalLink = /https?:\/\/\S+|\w+\.[a-z]{2,}\/\S*/i.test(text);
    return {
      text: text,
      hasVideo: hasVideo,
      hasImage: hasImage,
      hasExternalLink: hasExternalLink,
      hashtagCount: hashtagCount,
      isReply: false,
      isThreadStarter: /🧵/.test(text) || /(^|\s)1\/\d+/.test(text)
    };
  }

  // Live meters, so scroll/resize can reposition them and drop dead ones.
  var meters = [];

  // Place the meter just below its editor, flipping above and clamping to the
  // viewport when there is no room. Hidden entirely when the editor is not on
  // screen — if you cannot see the composer you are not typing in it.
  function positionMeter(entry) {
    var editor = entry.editor, meter = entry.meter;
    if (!editor.isConnected) { meter.remove(); return false; }
    if (meter.classList.contains("bangermeter-hidden")) return true;

    var r = editor.getBoundingClientRect();
    var vw = window.innerWidth, vh = window.innerHeight;
    if (r.width === 0 && r.height === 0) { meter.style.visibility = "hidden"; return true; }

    // Always write a position, even when about to hide: a fixed element with no
    // top/left falls back to its static position, which for a body child is
    // somewhere down the document.
    var mw = meter.offsetWidth || 260;
    var mh = meter.offsetHeight || 30;
    var top = r.bottom + 8;
    if (top + mh > vh - 8) top = r.top - mh - 8;      // flip above
    top = Math.max(8, Math.min(top, vh - mh - 8));    // clamp into the viewport
    var left = Math.max(8, Math.min(r.left, vw - mw - 8));
    meter.style.top = top + "px";
    meter.style.left = left + "px";

    // No visible composer, no chip.
    meter.style.visibility = (r.bottom < 0 || r.top > vh) ? "hidden" : "";
    return true;
  }

  function repositionMeters() {
    meters = meters.filter(positionMeter);
  }

  function ensureMeter(editor) {
    for (var i = 0; i < meters.length; i++) {
      if (meters[i].editor === editor) return meters[i].meter;
    }
    var meter = el("div", "bangermeter-meter");
    meter.setAttribute("role", "img");
    var host = editor.closest('div[data-testid^="tweetTextarea"]');
    var testid = editor.getAttribute("data-testid") || (host && host.getAttribute("data-testid"));
    if (testid) meter.setAttribute("data-bm-for", testid);
    var bar = el("div", "bangermeter-meter-track");
    bar.setAttribute("aria-hidden", "true");
    bar.appendChild(el("div", "bangermeter-meter-fill"));
    meter.appendChild(bar);
    meter.appendChild(el("span", "bangermeter-meter-score", ""));
    meter.appendChild(el("span", "bangermeter-meter-hints", ""));
    // Pinned to <body> so no ancestor of the composer can clip or cover it.
    document.body.appendChild(meter);
    meters.push({ editor: editor, meter: meter });
    return meter;
  }

  function updateMeter(editor) {
    if (!settings.scoreDrafts) return;
    var meter = ensureMeter(editor);
    if (!meter) return;
    // Read innerText once per keystroke (it forces layout) and pass it down.
    var text = editor.innerText || "";
    if (text.trim().length === 0) { meter.classList.add("bangermeter-hidden"); return; }
    meter.classList.remove("bangermeter-hidden");
    applyTheme(meter);
    // Match the composer's own width so the chip reads as part of it.
    var hostRect = (editor.closest('div[data-testid^="tweetTextarea"]') || editor)
      .getBoundingClientRect();
    if (hostRect.width > 120) meter.style.maxWidth = Math.round(hostRect.width) + "px";

    var result = BangermeterEngine.contentScore(draftFeatures(editor, text), settings);
    meter.setAttribute("aria-label", "Bangermeter draft score " + result.score + " out of 100");
    var fill = meter.querySelector(".bangermeter-meter-fill");
    fill.style.width = result.score + "%";
    fill.className = "bangermeter-meter-fill bangermeter-fill-" + scoreLevel(result.score);

    var scoreEl = meter.querySelector(".bangermeter-meter-score");
    scoreEl.textContent = "";
    scoreEl.appendChild(icon("bolt"));
    scoreEl.appendChild(document.createTextNode(String(result.score)));

    var hintsEl = meter.querySelector(".bangermeter-meter-hints");
    hintsEl.textContent = "";
    result.modifiers
      .filter(function (m) { return m.factor != null || m.id === "has_video"; })
      .forEach(function (m) {
        var bad = (m.factor != null && m.factor < 1) ||
          m.id === "engagement_bait" || m.id === "all_caps_shout";
        hintsEl.appendChild(el("span", bad ? "bangermeter-down" : "bangermeter-up",
          (bad ? "▼ " : "▲ ") + m.label));
      });

    repositionMeters();
  }

  document.addEventListener("input", function (ev) {
    var editor = ev.target && ev.target.closest &&
      ev.target.closest('div[data-testid^="tweetTextarea"] [contenteditable="true"], [data-testid^="tweetTextarea"][contenteditable="true"]');
    if (editor) updateMeter(editor);
  }, true);

  // The composer moves under the meter constantly: the dialog body scrolls as
  // the draft grows, the timeline scrolls behind it, and the window resizes.
  // capture:true so scrolls inside X's own overflow containers are seen too.
  var reposTimer = null;
  function scheduleReposition() {
    if (reposTimer) return;
    reposTimer = requestAnimationFrame(function () {
      reposTimer = null;
      repositionMeters();
    });
  }
  window.addEventListener("scroll", scheduleReposition, { capture: true, passive: true });
  window.addEventListener("resize", scheduleReposition, { passive: true });

  // ── scanning loop ─────────────────────────────────────────────────────────

  function scan() {
    scanTimer = null;
    if (settings.showBadges) {
      var articles = document.querySelectorAll('article[data-testid="tweet"]');
      articles.forEach(function (article) {
        var stamped = article.getAttribute("data-bangermeter");
        if (!stamped) { renderBadge(article); return; }
        // Fallback stamp means the tweet ID couldn't be resolved — treat as
        // always-stale so virtualized-list recycling can't pin an old score.
        if (stamped === "scored") { renderBadge(article); return; }
        // Virtualized list reuse: re-render when the underlying tweet changed
        var timeLink = article.querySelector('a[href*="/status/"] time');
        if (timeLink) {
          var href = timeLink.parentElement.getAttribute("href") || "";
          var m = href.match(/status\/(\d+)/);
          if (m && m[1] !== stamped) renderBadge(article);
        }
      });
    }
    if (settings.scoreDrafts) {
      document.querySelectorAll('div[data-testid^="tweetTextarea"] [contenteditable="true"]')
        .forEach(function (editor) { updateMeter(editor); });
    }
  }

  function scheduleScan() {
    if (scanTimer != null) return;
    scanTimer = setTimeout(scan, 350);
  }

  function fullRescan() {
    document.querySelectorAll("[data-bangermeter]").forEach(function (a) {
      a.removeAttribute("data-bangermeter");
    });
    scheduleScan();
  }

  var observer = new MutationObserver(scheduleScan);
  observer.observe(document.body, { childList: true, subtree: true });
  scheduleScan();
})();
