# Rebuilds extension/bangermeter.user.js from the extension sources.
# Single-file Tampermonkey build: styles.css (injected) + weights.js + scoring.js + content.js.
#
# PowerShell 5.1 gotchas this script deliberately works around:
#   - Get-Content without -Encoding UTF8 mangles the non-ASCII characters in the copy.
#   - Piping a string into ConvertTo-Json serializes PSPath metadata instead of the
#     string, so the CSS payload must be passed via -InputObject.
$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$ext = Join-Path $root "extension"
$out = Join-Path $ext "bangermeter.user.js"

$manifest = Get-Content (Join-Path $ext "manifest.json") -Raw -Encoding UTF8 | ConvertFrom-Json
$extVersion = $manifest.version

# Userscript versioning is independent of the extension's; bump the minor in step.
$userVersion = "1.7.3"

function Read-Src($name) {
    return (Get-Content (Join-Path $ext $name) -Raw -Encoding UTF8)
}

$css = Read-Src "styles.css"
$cssJson = ConvertTo-Json -InputObject "$css"

$header = @"
// ==UserScript==
// @name         Bangermeter — X Algorithm Scorer
// @namespace    bangermeter
// @version      $userVersion
// @description  Scores posts with X's actual published For You ranking weights (xai-org/x-algorithm, Aug 13 2026 release) using the real Phoenix weighted-sum arithmetic.
// @match        https://x.com/*
// @match        https://twitter.com/*
// @grant        none
// @run-at       document-idle
// ==/UserScript==

// Single-file build generated by store-assets/make-userscript.ps1 from extension/
// (weights.js + scoring.js + content.js + styles.css) at extension v$extVersion.
// The settings popup is not available in the userscript version; defaults apply
// (badges ON, draft meter ON, theme AUTO, out-of-network OFF, mutual-follow OFF,
// 2023 verified boost OFF — edit BANGERMETER_DEFAULT_SETTINGS below to change).
(function () {
  var s = document.createElement('style');
  s.textContent = $cssJson;
  (document.head || document.documentElement).appendChild(s);
})();

"@

$parts = @(
    $header,
    (Read-Src "weights.js"),
    (Read-Src "scoring.js"),
    (Read-Src "content.js")
)

# -Encoding utf8 on Out-File emits a BOM in 5.1; Tampermonkey tolerates it, but
# writing the bytes directly keeps the file byte-identical across rebuilds.
$text = ($parts -join "`n")
[System.IO.File]::WriteAllText($out, $text, (New-Object System.Text.UTF8Encoding($false)))

$lines = ($text -split "`n").Count
Write-Host "built $out  (userscript v$userVersion, extension v$extVersion, $lines lines)"
